#!/usr/bin/env python3
# Auto-generated by hermes-skill-onboard/scripts/setup_workflow.py
# Skill:     {SKILL_NAME}
# Channel:   #{CHANNEL_NAME} ({CHANNEL_ID})
# Generated: {GENERATED_AT}
#
# Usage: python deliver.py <path-to-report.md>
#
# Deterministic delivery pipeline:
#   1. Read content file
#   2. Create Slack canvas
#   3. Send notification with canvas link (fallback to inline if canvas fails)

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SKILL_NAME = "{SKILL_NAME}"
CHANNEL_ID = "{CHANNEL_ID}"
CHANNEL_NAME = "{CHANNEL_NAME}"
SLACK_SCRIPTS = "{SLACK_SCRIPTS}"
SLACK_WORKSPACE_URL = "https://eugeneoncloud.slack.com/docs/T09M25MA56E"


def _parse_canvas_id(stdout: str) -> str | None:
    """Extract canvas ID from create-canvas.py stdout."""
    for line in stdout.splitlines():
        if "Canvas ID:" in line:
            return line.split("Canvas ID:")[-1].strip()
    return None


def create_canvas(title: str, content_file: str) -> str | None:
    """Create a Slack canvas. Returns canvas_id or None on failure."""
    result = subprocess.run(
        [
            sys.executable,
            f"{SLACK_SCRIPTS}/create-canvas.py",
            "--title", title,
            "--channel-id", CHANNEL_ID,
            "--content-file", content_file,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"[deliver] canvas creation failed: {result.stderr.strip()}", file=sys.stderr)
        return None
    canvas_id = _parse_canvas_id(result.stdout)
    if not canvas_id:
        print(f"[deliver] could not parse canvas ID from output: {result.stdout.strip()}", file=sys.stderr)
    return canvas_id


def send_notification(message: str) -> bool:
    """Send a message to the skill's Slack channel."""
    result = subprocess.run(
        [
            sys.executable,
            f"{SLACK_SCRIPTS}/send-message.py",
            "--channel", CHANNEL_ID,
            "--message", message,
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"[deliver] notification failed: {result.stderr.strip()}", file=sys.stderr)
        return False
    return True


def run(content_file: str) -> int:
    content_path = Path(content_file)
    if not content_path.exists():
        print(f"[deliver] ERROR: content file not found: {content_file}", file=sys.stderr)
        return 1

    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d %H:%M UTC")
    title = f"{SKILL_NAME} — {today}"

    canvas_id = create_canvas(title, str(content_path))

    if canvas_id:
        canvas_url = f"{SLACK_WORKSPACE_URL}/{canvas_id}"
        message = (
            f"📋 {SKILL_NAME} Report Updated\n"
            f"📅 {today}\n"
            f"🔗 <{canvas_url}|View Canvas>"
        )
    else:
        # Fallback: send a short inline excerpt
        try:
            excerpt = content_path.read_text(encoding="utf-8")[:800].strip()
        except Exception:
            excerpt = "(could not read report)"
        message = (
            f"📋 {SKILL_NAME} Report\n"
            f"📅 {today}\n"
            f"⚠️ Canvas unavailable — excerpt below:\n\n{excerpt}"
        )

    ok = send_notification(message)
    return 0 if ok else 1


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <content-file>", file=sys.stderr)
        sys.exit(1)
    sys.exit(run(sys.argv[1]))
